travis:
  secure:
    BINSTAR_TOKEN: kDrbnxCLx/CPIRJjA9GIlwZD+O5ZidvTZhThNVSUdpa9ERAkdiTuqyOj2CNd4vD4Bee1PCMNuW+fmLVYpUS6lHi6NKWegvFW0rVjgv3c7vULa+3h3/sr/Sv9LMWJMFdbYoRX79M6cpAY0Rv3tmlbjtA5Plt6/Ng8DkpKzke73D5jcLGjdinYQvalX6erFE52KzBJyUyMtAimbBcVJgs0bg7eVWrrRFqjQyJWubF2JiUkQsp8d7+jnUBnNqUQa2RpIrzYBKQ8ZT3JcjAlz50Pp3g8jsRvakdMfTrFHsHO4F2ujUg3Be8ExbkKMM8fzB5QWlmaisgkAAnMjAz9GvaAFgFMeZFE93tAYDrhm7whDcg1YLC/CpY8pQT38YrSkjR0OFq8yB1WZCuvq09fo7hRAJUk2dG1uq8WurkpXWwlIoPAzDdE0GnR7nif4AbMxWZlS2hFqwGu5YO8wl8i/2ZO98CZQbo1dW3GVKdQxbqHqi6lNdK+6NcqtJKI+jR2WwBfBXSXi3T3XUHu721sBGEx5e3G3BCysS9AFntxLwWKRBURg5olKy3V8VXatrwF+yXqLYKzuAZYFAMt1NvqdAi/0FdpUm1Eo3T8DhfefnlyWSg66m6xCJLTi+lpvRjgXzLX4dDab/QcF6AiCihRTHuvRbYcL2lKLvCI+MkGEu1uVrM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
